service: ngrokast

package:
  individually: true
  exclude:
    - ./**

provider:
  name: aws
  runtime: nodejs6.10
  apiKeys:
    - ngrokastKey

functions:
  fetch:
    handler: handler.fetch
    package:
      include:
        - handler.js
    events:
      - http:
          path: fetch
          method: get
          cors: true
          private: true
  broadcast:
    handler: broadcast/handler.broadcast
    package:
      include:
        - ./broadcast/**
        - ./secrets.json
    events:
      - http:
          path: broadcast
          method: post
          cors: true
          private: true
